---
- name: Prepare nodes for Kafka download
  ansible.builtin.include_tasks:
    file: prepare_nodes.yml

- name: Download Tarball and Setup kafka home
  when: download_tarball | bool
  ansible.builtin.include_tasks: 
    file: setup_home.yml

- name: Deploy single instance kafka
  when:
    - standalone is defined
    - standalone | bool
    - multinode is not defined or not multinode | bool
  ansible.builtin.include_tasks:
    file: standalone.yml

- name: Deploy Multinode kafka Cluster
  when:
    - multinode is defined
    - multinode | bool
    - standalone is not defined or not standalone | bool
  ansible.builtin.include_tasks:
    file: multinode.yml