---
- name: Prepare nodes for Kafka download
  ansible.builtin.include_tasks: prepare_nodes.yml

- name: Download Tarball and Setup kafka home
  when: download_tarball | bool
  ansible.builtin.include_tasks: setup_home.yml
  
- name: Deploy single instance kafka
  when:
    - single_instance | bool
    - not multinode_cluster | bool
  ansible.builtin.include_tasks:
    file: single.yml

- name: Deploy single instance kafka
  when:
    - not single_instance | bool
    - multinode_cluster | bool
  ansible.builtin.include_tasks:
    file: multinode.yml