---
- name: Prepare nodes for Kafka download
  ansible.builtin.include_tasks: prepare_nodes.yml

- name: Download Tarball and Setup kafka home
  when: download_tarball | bool
  ansible.builtin.include_tasks: setup_home.yml

- name: Set kafka tarball name
  ansible.builtin.set_fact:
    kafka_tarball_name: "{{ kafka_url | urlsplit('path') | basename }}"

- name: Check if kafka home is empty
  ansible.builtin.find:
    paths: "{{ kafka_home }}"
    file_type: any
    hidden: true
  register: kafka_home_find

- name: set kafka_home_empty
  ansible.builtin.set_fact:
    kafka_home_empty: "{{ (kafka_home_find.matched | default(0)) == 0 }}"

- name: Assert kafka home is empty
  ansible.builtin.assert:
    that: kafka_home_empty | bool
    fail_msg: "Kafka home is not empty"

- name: Push kafka tarball to managed hosts
  ansible.builtin.unarchive:
    src: "{{ kafka_url }}"
    dest: "{{ kafka_home }}"
    remote_src: true
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    extra_opts: 
      - "--strip-components=1"

- name: Deploy single instance kafka
  when:
    - single_instance | bool
    - not multinode_cluster | bool
  ansible.builtin.include_tasks:
    file: single.yml

- name: Deploy single instance kafka
  when:
    - not single_instance | bool
    - multinode_cluster | bool
  ansible.builtin.include_tasks:
    file: multinode.yml