- name: Ensure there's a line in /etc/hosts for self-resolved hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    state: present
  
- name: Ensure the server.properties file is deployed
  ansible.builtin.template:
    src: templates/server.properties.single.j2
    dest: "{{ kafka_home }}/config/server.properties"
    backup: true

- name: Ensure the SystemD unit file for kafka is deployed
  ansible.builtin.template:
    src: templates/kafka.service.j2
    dest: /etc/systemd/system/kafka.service

- name: Generate Kafka Cluster UUID
  register: kafka_cluster_uuid_out
  ansible.builtin.command: "{{ kafka_home }}/bin/kafka-storage.sh random-uuid"

- name: Set kafka cluster UUID fact
  ansible.builtin.set_fact:
    kafka_cluster_uuid: "{{ kafka_cluster_uuid_out.stdout }}"

- name: Ensure Cluster UUID is formatted
  ansible.builtin.command: |
    {{ kafka_home }}/bin/kafka-storage.sh \
      -t {{ kafka_cluster_uuid }} \
      --config {{ kafka_home }}/config/server.properties

- name: Ensure SystemD Daemon Reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Ensure kafka service is enabled and started
  ansible.builtin.service:
    name: kafka
    state: started
    enabled: true
