- name: Generate Kafka Cluster UUID
  register: kafka_cluster_uuid_out
  ansible.builtin.command: "{{ kafka_home }}/bin/kafka-storage.sh random-uuid"

- name: Set kafka cluster UUID fact
  ansible.builtin.set_fact:
    kafka_cluster_uuid: "{{ kafka_cluster_uuid_out.stdout }}"

- name: Debug kafka cluster UUID fact
  ansible.builtin.debug:
    var: kafka_cluster_uuid

- name: Ensure there's a line in /etc/hosts for self-resolved hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  
- name: Ensure the server.properties file is deployed
  ansible.builtin.template:
    src: templates/server.properties.j2
    dest: "{{ kafka_home }}/conf/server.properties"
    backup: true
